from admyral.workflow import workflow, Webhook
from admyral.typings import JsonValue
from admyral.actions import (
    virus_total_analyze_url,
    send_slack_message,
    openai_chat_completion,
)


@workflow(description="Analyze an URL using VirusTotal", triggers=[Webhook()])
def virus_total_workflow(payload: dict[str, JsonValue]):
    # get the analyis result from VirusTotal
    analysis_result = virus_total_analyze_url(
        url=payload["url"], secrets={"VIRUS_TOTAL_SECRET": "virus_total"}
    )

    # ask the AI to analyze the result
    ai_summary = openai_chat_completion(
        model="gpt-4o",
        prompt=f"You are an expert security analyst. You received the subsequent url analyis result form VirusTotal. \
            Can you briefly state which website it is about and summarize \
            in a short and precise manner if the website is safe to visit? \
            Here is the alert:\n{analysis_result}",
        secrets={"OPENAI_SECRET": "openai_secret"},
    )

    # send the summary to a Slack channel
    send_slack_message(
        channel_id="C06QP0KV1L2",
        text=f"INFORMATION: The URL {payload['url']} has been analyzed by VirusTotal.",
        blocks=[
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Information: URL {payload['url']} analysis by VirusTotal.*",
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "Please note that the following information is generated by an AI model and should be verified by a human expert.",
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"AI VirusTotal Result Summary:\n{ai_summary}",
                },
            },
        ],
        secrets={"SLACK_SECRET": "slack_secret"},
    )
